### ISSUE TITLE
Parse

### ISSUE THREAD

**Issue by telbohtimy** [Jordoser/Tonight401#2]
Hi,
I put on a separate branch(In case its broken I haven tested it all) code that gets the venue names from parse.  It does this fine the thing is it doesn't do this fast enough. When you first load up the app the list will be empty but if you turn your phone side ways it adds the contents just fine and we return your phone back it will add the bar names again(this is due to me not clearing the list every onCreate).  I'm not sure how to get to add right at the start up though

**Comment by Jordoser** [comment]
I'll take a look when I get home, are you loading that info in the main
activity or the splash screen?

**Comment by telbohtimy** [comment]
Main activity.

**Comment by Jordoser** [comment]
Ok cool I'll take a look at it, I might try moving it to the splash screen
so we can hide that time and we can just store that data in a controller
class and in the activity just read from there. Probably a Singleton

**Comment by telbohtimy** [comment]
Moving it to the splash screened worked.  Might want to increase the splash screen time for good measure
